version: 1.0.{build}-{branch}

clone_depth: 1

platform:
# - x86
- x64

environment:
  UPX_VER: 3.95

install:
  - appveyor DownloadFile https://fossil-scm.org/home/zip/trunk/Fossil-trunk.zip
  - 7z x *.zip
  - appveyor DownloadFile https://www.openssl.org/source/openssl-1.1.1e.tar.gz
  - 7z e *.tar.gz
  - 7z x *.tar -oFossil-trunk\compat
  - ppm install dmake
  - appveyor DownloadFile https://github.com/upx/upx/releases/download/v%UPX_VER%/upx-%UPX_VER%-win64.zip
  - 7z e upx-*.zip */*.exe
  - cd Fossil-trunk\win
  - buildmsvc.bat FOSSIL_ENABLE_JSON=1 FOSSIL_ENABLE_TCL=1 FOSSIL_ENABLE_SSL=1 FOSSIL_BUILD_SSL=1
  - copy /b ..\msvcbld\fossil.exe ..\..
  - cd ..\..
  - upx fossil.exe
  - fossil version
  - ps: Add-AppveyorMessage -Message $(./fossil version)

build: off

artifacts:
  - path: fossil.exe
    name: Fossil for Windows with JSON support
