version: 1.0.{build}-{branch}

install:
  - appveyor DownloadFile https://fossil-scm.org/home/zip/trunk/Fossil-trunk.zip
  - 7z x *.zip
  - cd Fossil-trunk\win
  - buildmsvc.bat FOSSIL_ENABLE_JSON=1

build: off
